import React from "react";
import "../style/AboutUs.css"; // Import the CSS file for styling

function AboutUs() {
  return (
    <div className="about-us-container">
      <h1 className="about-us-title">About Us</h1>
      <div className="about-us-content">
        <p>
          Welcome to our library website! We are team Ollek, a group of
          passionate individuals who never even touched books and definitely don't believe in their power to
          inspire, educate, and entertain. Our mission is to create a
          platform where book lovers can find and review the books they adore.
        </p>
        <p>
          We aim to build a community that shares insights, recommendations, and
          reviews to help readers discover their next great read.
        </p>
        <p>
          Thank you for visiting our site, and we hope you enjoy your time with
          us!
        </p>
        <p>
          This text was also definitely written by ourselves and not generated by Chatgpt, because we just needed some text to fill in the blanks. And always remember stay Ollek!
        </p>
      </div>

      <div className="team-members">
        <h2>Meet the Team</h2>
        <div className="team-cards-container">
          <div className="team-card">
            <img src="/team/raphael.png" alt="Placeholder" className="team-member-img" />
            <h3>Raphael Schmitz</h3>
            <p>The lazy guy that manages the other lazy guys</p>
          </div>
          <div className="team-card">
            <img src="/team/felix.jpg" alt="Placeholder" className="team-member-img" />
            <h3>Felix Welter</h3>
            <p>The lazy guy, that develops and breaks stuff</p>
          </div>
          <div className="team-card">
            <img src="/team/ken.png" alt="Placeholder" className="team-member-img" />
            <h3>Ken Theis</h3>
            <p>The lazy guy, that's supporting Felix (mostly on an emotional level)</p>
          </div>
          <div className="team-card">
            <img src="/team/andrei.png" alt="Placeholder" className="team-member-img" />
            <h3>Andrei Grigore</h3>
            <p>The lazy guy, that's also Romanian and analyzes the business</p>
          </div>
          <div className="team-card">
            <img src="/team/sadin.jpg" alt="Placeholder" className="team-member-img" />
            <h3>Sadin Avdusinovic</h3>
            <p>The lazy guy, that's also analyzing the business and doing most of the other stuff actually</p>
          </div>
          <div className="team-card">
            <img src="/team/kim.jpg" alt="Placeholder" className="team-member-img" />
            <h3>Kim Meyers</h3>
            <p>The lazy guy, that's managing our data</p>
          </div>
        </div>
      </div>
    </div>
    
  );
}

export default AboutUs;
